_extends: release-drafter-poc:.github/release-drafter.yaml
name-template: "onprem_k8s_module_1-v$RESOLVED_VERSION"
tag-template: "onprem_k8s_module_1-v$RESOLVED_VERSION"
tag-prefix: onprem_k8s_module_1-v
include-paths:
  - "onprem_k8s_module_1"
