name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: "fix"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
      - "/🐛/"
      - "/bug/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - "/feature/i"
      - "/✨/"
  - label: "major"
    title:
      - "/🚨/"
    branch:
      - '/breaking\/.+/'
